# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("http://10.90.90.90/")
    self.driver.set_window_size(1164, 902)
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "Login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-wrapper:nth-child(2) > .el-submenuTitle > .el-submenu__title > .el-submenu__icon-arrow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened > .el-menu > .menu-wrapper:nth-child(2) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-leaf:nth-child(1) > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-leaf:nth-child(2) > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-leaf:nth-child(3) > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-leaf:nth-child(4) > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-leaf:nth-child(5) > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-leaf:nth-child(6) > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_1_column_1 > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row--striped > .el-table_1_column_1 > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, "td > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .sx-select").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .sx-select").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .sx-select").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .sx-select").click()
    self.driver.find_element(By.ID, "apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sx-form:nth-child(4) > tr:nth-child(2) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sx-form > tr:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sx-form:nth-child(4) > tr:nth-child(3) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sx-form:nth-child(4) > tr:nth-child(4) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) > td:nth-child(2)").click()
  
